### ISSUE TITLE
`repr` parameters are inconsistent between SE3BatchNorm and SE3Conv

### ISSUE THREAD

**Issue by jatentaki** [mariogeiger/se3cnn#3]
As can be seen [here](https://github.com/mariogeiger/se3cnn/pull/2/files#diff-3d678d9f3a13965aabbb88f6227a8555R14), one needs to convert the representation manually to make them interoperate.

This is because BN treats [order 1](https://github.com/mariogeiger/se3cnn/blob/master/se3cnn/batchnorm.py#L56) as scalars, for some reason.

**Comment by mariogeiger** [comment]
This is not a bug. It is a poor choice of notation.
Some time `Rs_in` contains couples of `(multiplicity, order of irreducible representation)` and some times `(multiplicity, dimension of the representation)`.
There is a reason why both are used. Some operation are specific to the irreducible representations, it is the case of `SE3Kernel` for instance, but some other like `SE3BatchNorm` are more general therefore it ask for the dimension instead of the order.

Note that the conversion from order to dimension is easy : `d = 2l+1`
